# fly.toml app configuration file generated for products-manager on 2023-07-19T19:31:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "products-manager"
primary_region = "mad"
# console_command = "node /app/index.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
